name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *' # 毎日 9:00(JST) に実行
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Log into DockerHub'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: shono09835
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: 'Checkout current develop'
        uses: actions/checkout@v4
      - name: 'Checkout current develop'
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/docker-github-actions-runner:ubuntu-jammy
